// https://projecteuler.net/problem=2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var fibonacci = [1, 2];
var sumEvenValued = 2;

var findFibonacci = function (upperLimit) {
	while(fibonacci[fibonacci.length - 1] < upperLimit) {
		var newElement = fibonacci[fibonacci.length - 1] + fibonacci[fibonacci.length - 2];
		if (newElement > upperLimit) {
			break; 
		} else if (newElement % 2 === 0) {
			fibonacci.push(newElement);
			sumEvenValued += newElement;
		} else {
			fibonacci.push(newElement);
		};
	}
	console.log("Fibonacci Secquence: " + fibonacci);
	console.log("the sum of the even-valued terms: " + sumEvenValued);

}

findFibonacci(4000000);

