# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db04e7b241db3ba6a266ba241511a9ea51d22dd9980cac7af4b053c2642a026339db8d147b274d31886aae60a784c19cbeaca61972b3e3c6f6392983bfd96a60

test:
  secret_key_base: f69cfc5cae0f0b7f7f5d276b32a49c8e214df9c2a95e85988a617e50cdecb37af88cf22eb6d813b3ca2beb12b055422bee005f4d1896a5e594124d69303472ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
